/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
	"time"
)

// checks if the ListProductsRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProductsRequestFilter{}

// ListProductsRequestFilter struct for ListProductsRequestFilter
type ListProductsRequestFilter struct {
	CreatedAtStart *time.Time `json:"createdAtStart,omitempty"`
	CreatedAtEnd *time.Time `json:"createdAtEnd,omitempty"`
	UpdatedAtStart *time.Time `json:"updatedAtStart,omitempty"`
	UpdatedAtEnd *time.Time `json:"updatedAtEnd,omitempty"`
	Status *bool `json:"status,omitempty"`
}

// NewListProductsRequestFilter instantiates a new ListProductsRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProductsRequestFilter() *ListProductsRequestFilter {
	this := ListProductsRequestFilter{}
	return &this
}

// NewListProductsRequestFilterWithDefaults instantiates a new ListProductsRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProductsRequestFilterWithDefaults() *ListProductsRequestFilter {
	this := ListProductsRequestFilter{}
	return &this
}

// GetCreatedAtStart returns the CreatedAtStart field value if set, zero value otherwise.
func (o *ListProductsRequestFilter) GetCreatedAtStart() time.Time {
	if o == nil || IsNil(o.CreatedAtStart) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAtStart
}

// GetCreatedAtStartOk returns a tuple with the CreatedAtStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsRequestFilter) GetCreatedAtStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAtStart) {
		return nil, false
	}
	return o.CreatedAtStart, true
}

// HasCreatedAtStart returns a boolean if a field has been set.
func (o *ListProductsRequestFilter) HasCreatedAtStart() bool {
	if o != nil && !IsNil(o.CreatedAtStart) {
		return true
	}

	return false
}

// SetCreatedAtStart gets a reference to the given time.Time and assigns it to the CreatedAtStart field.
func (o *ListProductsRequestFilter) SetCreatedAtStart(v time.Time) {
	o.CreatedAtStart = &v
}

// GetCreatedAtEnd returns the CreatedAtEnd field value if set, zero value otherwise.
func (o *ListProductsRequestFilter) GetCreatedAtEnd() time.Time {
	if o == nil || IsNil(o.CreatedAtEnd) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAtEnd
}

// GetCreatedAtEndOk returns a tuple with the CreatedAtEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsRequestFilter) GetCreatedAtEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAtEnd) {
		return nil, false
	}
	return o.CreatedAtEnd, true
}

// HasCreatedAtEnd returns a boolean if a field has been set.
func (o *ListProductsRequestFilter) HasCreatedAtEnd() bool {
	if o != nil && !IsNil(o.CreatedAtEnd) {
		return true
	}

	return false
}

// SetCreatedAtEnd gets a reference to the given time.Time and assigns it to the CreatedAtEnd field.
func (o *ListProductsRequestFilter) SetCreatedAtEnd(v time.Time) {
	o.CreatedAtEnd = &v
}

// GetUpdatedAtStart returns the UpdatedAtStart field value if set, zero value otherwise.
func (o *ListProductsRequestFilter) GetUpdatedAtStart() time.Time {
	if o == nil || IsNil(o.UpdatedAtStart) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtStart
}

// GetUpdatedAtStartOk returns a tuple with the UpdatedAtStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsRequestFilter) GetUpdatedAtStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAtStart) {
		return nil, false
	}
	return o.UpdatedAtStart, true
}

// HasUpdatedAtStart returns a boolean if a field has been set.
func (o *ListProductsRequestFilter) HasUpdatedAtStart() bool {
	if o != nil && !IsNil(o.UpdatedAtStart) {
		return true
	}

	return false
}

// SetUpdatedAtStart gets a reference to the given time.Time and assigns it to the UpdatedAtStart field.
func (o *ListProductsRequestFilter) SetUpdatedAtStart(v time.Time) {
	o.UpdatedAtStart = &v
}

// GetUpdatedAtEnd returns the UpdatedAtEnd field value if set, zero value otherwise.
func (o *ListProductsRequestFilter) GetUpdatedAtEnd() time.Time {
	if o == nil || IsNil(o.UpdatedAtEnd) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAtEnd
}

// GetUpdatedAtEndOk returns a tuple with the UpdatedAtEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsRequestFilter) GetUpdatedAtEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAtEnd) {
		return nil, false
	}
	return o.UpdatedAtEnd, true
}

// HasUpdatedAtEnd returns a boolean if a field has been set.
func (o *ListProductsRequestFilter) HasUpdatedAtEnd() bool {
	if o != nil && !IsNil(o.UpdatedAtEnd) {
		return true
	}

	return false
}

// SetUpdatedAtEnd gets a reference to the given time.Time and assigns it to the UpdatedAtEnd field.
func (o *ListProductsRequestFilter) SetUpdatedAtEnd(v time.Time) {
	o.UpdatedAtEnd = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListProductsRequestFilter) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsRequestFilter) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListProductsRequestFilter) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ListProductsRequestFilter) SetStatus(v bool) {
	o.Status = &v
}

func (o ListProductsRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProductsRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAtStart) {
		toSerialize["createdAtStart"] = o.CreatedAtStart
	}
	if !IsNil(o.CreatedAtEnd) {
		toSerialize["createdAtEnd"] = o.CreatedAtEnd
	}
	if !IsNil(o.UpdatedAtStart) {
		toSerialize["updatedAtStart"] = o.UpdatedAtStart
	}
	if !IsNil(o.UpdatedAtEnd) {
		toSerialize["updatedAtEnd"] = o.UpdatedAtEnd
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableListProductsRequestFilter struct {
	value *ListProductsRequestFilter
	isSet bool
}

func (v NullableListProductsRequestFilter) Get() *ListProductsRequestFilter {
	return v.value
}

func (v *NullableListProductsRequestFilter) Set(val *ListProductsRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableListProductsRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableListProductsRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProductsRequestFilter(val *ListProductsRequestFilter) *NullableListProductsRequestFilter {
	return &NullableListProductsRequestFilter{value: val, isSet: true}
}

func (v NullableListProductsRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProductsRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


