/*
product/product.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// ProductCreateProductResponseV2 struct for ProductCreateProductResponseV2
type ProductCreateProductResponseV2 struct {
	Id *string `json:"id,omitempty"`
}

// NewProductCreateProductResponseV2 instantiates a new ProductCreateProductResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductCreateProductResponseV2() *ProductCreateProductResponseV2 {
	this := ProductCreateProductResponseV2{}
	return &this
}

// NewProductCreateProductResponseV2WithDefaults instantiates a new ProductCreateProductResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductCreateProductResponseV2WithDefaults() *ProductCreateProductResponseV2 {
	this := ProductCreateProductResponseV2{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductCreateProductResponseV2) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreateProductResponseV2) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductCreateProductResponseV2) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductCreateProductResponseV2) SetId(v string) {
	o.Id = &v
}

func (o ProductCreateProductResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableProductCreateProductResponseV2 struct {
	value *ProductCreateProductResponseV2
	isSet bool
}

func (v NullableProductCreateProductResponseV2) Get() *ProductCreateProductResponseV2 {
	return v.value
}

func (v *NullableProductCreateProductResponseV2) Set(val *ProductCreateProductResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableProductCreateProductResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableProductCreateProductResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductCreateProductResponseV2(val *ProductCreateProductResponseV2) *NullableProductCreateProductResponseV2 {
	return &NullableProductCreateProductResponseV2{value: val, isSet: true}
}

func (v NullableProductCreateProductResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductCreateProductResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


