/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the ProductListVariantsBySkuRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductListVariantsBySkuRequest{}

// ProductListVariantsBySkuRequest struct for ProductListVariantsBySkuRequest
type ProductListVariantsBySkuRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Sku *string `json:"sku,omitempty"`
}

// NewProductListVariantsBySkuRequest instantiates a new ProductListVariantsBySkuRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductListVariantsBySkuRequest() *ProductListVariantsBySkuRequest {
	this := ProductListVariantsBySkuRequest{}
	return &this
}

// NewProductListVariantsBySkuRequestWithDefaults instantiates a new ProductListVariantsBySkuRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductListVariantsBySkuRequestWithDefaults() *ProductListVariantsBySkuRequest {
	this := ProductListVariantsBySkuRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductListVariantsBySkuRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductListVariantsBySkuRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductListVariantsBySkuRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductListVariantsBySkuRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *ProductListVariantsBySkuRequest) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductListVariantsBySkuRequest) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *ProductListVariantsBySkuRequest) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *ProductListVariantsBySkuRequest) SetSku(v string) {
	o.Sku = &v
}

func (o ProductListVariantsBySkuRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductListVariantsBySkuRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	return toSerialize, nil
}

type NullableProductListVariantsBySkuRequest struct {
	value *ProductListVariantsBySkuRequest
	isSet bool
}

func (v NullableProductListVariantsBySkuRequest) Get() *ProductListVariantsBySkuRequest {
	return v.value
}

func (v *NullableProductListVariantsBySkuRequest) Set(val *ProductListVariantsBySkuRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductListVariantsBySkuRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductListVariantsBySkuRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductListVariantsBySkuRequest(val *ProductListVariantsBySkuRequest) *NullableProductListVariantsBySkuRequest {
	return &NullableProductListVariantsBySkuRequest{value: val, isSet: true}
}

func (v NullableProductListVariantsBySkuRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductListVariantsBySkuRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


