/*
product/product.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// EntitymanagerUpdateAttributeRequest struct for EntitymanagerUpdateAttributeRequest
type EntitymanagerUpdateAttributeRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Code *string `json:"code,omitempty"`
	EntityData *EntitymanagerEntityIdentifier `json:"entityData,omitempty"`
	EntityId *string `json:"entityId,omitempty"`
	Payload *EntitymanagerUpdateAttributeRequestPayload `json:"payload,omitempty"`
	FieldMask []string `json:"fieldMask,omitempty"`
}

// NewEntitymanagerUpdateAttributeRequest instantiates a new EntitymanagerUpdateAttributeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitymanagerUpdateAttributeRequest() *EntitymanagerUpdateAttributeRequest {
	this := EntitymanagerUpdateAttributeRequest{}
	return &this
}

// NewEntitymanagerUpdateAttributeRequestWithDefaults instantiates a new EntitymanagerUpdateAttributeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitymanagerUpdateAttributeRequestWithDefaults() *EntitymanagerUpdateAttributeRequest {
	this := EntitymanagerUpdateAttributeRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *EntitymanagerUpdateAttributeRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *EntitymanagerUpdateAttributeRequest) SetCode(v string) {
	o.Code = &v
}

// GetEntityData returns the EntityData field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetEntityData() EntitymanagerEntityIdentifier {
	if o == nil || isNil(o.EntityData) {
		var ret EntitymanagerEntityIdentifier
		return ret
	}
	return *o.EntityData
}

// GetEntityDataOk returns a tuple with the EntityData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetEntityDataOk() (*EntitymanagerEntityIdentifier, bool) {
	if o == nil || isNil(o.EntityData) {
    return nil, false
	}
	return o.EntityData, true
}

// HasEntityData returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasEntityData() bool {
	if o != nil && !isNil(o.EntityData) {
		return true
	}

	return false
}

// SetEntityData gets a reference to the given EntitymanagerEntityIdentifier and assigns it to the EntityData field.
func (o *EntitymanagerUpdateAttributeRequest) SetEntityData(v EntitymanagerEntityIdentifier) {
	o.EntityData = &v
}

// GetEntityId returns the EntityId field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetEntityId() string {
	if o == nil || isNil(o.EntityId) {
		var ret string
		return ret
	}
	return *o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetEntityIdOk() (*string, bool) {
	if o == nil || isNil(o.EntityId) {
    return nil, false
	}
	return o.EntityId, true
}

// HasEntityId returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasEntityId() bool {
	if o != nil && !isNil(o.EntityId) {
		return true
	}

	return false
}

// SetEntityId gets a reference to the given string and assigns it to the EntityId field.
func (o *EntitymanagerUpdateAttributeRequest) SetEntityId(v string) {
	o.EntityId = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetPayload() EntitymanagerUpdateAttributeRequestPayload {
	if o == nil || isNil(o.Payload) {
		var ret EntitymanagerUpdateAttributeRequestPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetPayloadOk() (*EntitymanagerUpdateAttributeRequestPayload, bool) {
	if o == nil || isNil(o.Payload) {
    return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasPayload() bool {
	if o != nil && !isNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given EntitymanagerUpdateAttributeRequestPayload and assigns it to the Payload field.
func (o *EntitymanagerUpdateAttributeRequest) SetPayload(v EntitymanagerUpdateAttributeRequestPayload) {
	o.Payload = &v
}

// GetFieldMask returns the FieldMask field value if set, zero value otherwise.
func (o *EntitymanagerUpdateAttributeRequest) GetFieldMask() []string {
	if o == nil || isNil(o.FieldMask) {
		var ret []string
		return ret
	}
	return o.FieldMask
}

// GetFieldMaskOk returns a tuple with the FieldMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerUpdateAttributeRequest) GetFieldMaskOk() ([]string, bool) {
	if o == nil || isNil(o.FieldMask) {
    return nil, false
	}
	return o.FieldMask, true
}

// HasFieldMask returns a boolean if a field has been set.
func (o *EntitymanagerUpdateAttributeRequest) HasFieldMask() bool {
	if o != nil && !isNil(o.FieldMask) {
		return true
	}

	return false
}

// SetFieldMask gets a reference to the given []string and assigns it to the FieldMask field.
func (o *EntitymanagerUpdateAttributeRequest) SetFieldMask(v []string) {
	o.FieldMask = v
}

func (o EntitymanagerUpdateAttributeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.EntityData) {
		toSerialize["entityData"] = o.EntityData
	}
	if !isNil(o.EntityId) {
		toSerialize["entityId"] = o.EntityId
	}
	if !isNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !isNil(o.FieldMask) {
		toSerialize["fieldMask"] = o.FieldMask
	}
	return json.Marshal(toSerialize)
}

type NullableEntitymanagerUpdateAttributeRequest struct {
	value *EntitymanagerUpdateAttributeRequest
	isSet bool
}

func (v NullableEntitymanagerUpdateAttributeRequest) Get() *EntitymanagerUpdateAttributeRequest {
	return v.value
}

func (v *NullableEntitymanagerUpdateAttributeRequest) Set(val *EntitymanagerUpdateAttributeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitymanagerUpdateAttributeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitymanagerUpdateAttributeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitymanagerUpdateAttributeRequest(val *EntitymanagerUpdateAttributeRequest) *NullableEntitymanagerUpdateAttributeRequest {
	return &NullableEntitymanagerUpdateAttributeRequest{value: val, isSet: true}
}

func (v NullableEntitymanagerUpdateAttributeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitymanagerUpdateAttributeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


