/*
product/product.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// ProductBulkUpdateRequestV2Payload struct for ProductBulkUpdateRequestV2Payload
type ProductBulkUpdateRequestV2Payload struct {
	UpdateMask *ProductFieldMask `json:"updateMask,omitempty"`
	Attributes *map[string]ProtobufAny `json:"attributes,omitempty"`
}

// NewProductBulkUpdateRequestV2Payload instantiates a new ProductBulkUpdateRequestV2Payload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductBulkUpdateRequestV2Payload() *ProductBulkUpdateRequestV2Payload {
	this := ProductBulkUpdateRequestV2Payload{}
	return &this
}

// NewProductBulkUpdateRequestV2PayloadWithDefaults instantiates a new ProductBulkUpdateRequestV2Payload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductBulkUpdateRequestV2PayloadWithDefaults() *ProductBulkUpdateRequestV2Payload {
	this := ProductBulkUpdateRequestV2Payload{}
	return &this
}

// GetUpdateMask returns the UpdateMask field value if set, zero value otherwise.
func (o *ProductBulkUpdateRequestV2Payload) GetUpdateMask() ProductFieldMask {
	if o == nil || isNil(o.UpdateMask) {
		var ret ProductFieldMask
		return ret
	}
	return *o.UpdateMask
}

// GetUpdateMaskOk returns a tuple with the UpdateMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateRequestV2Payload) GetUpdateMaskOk() (*ProductFieldMask, bool) {
	if o == nil || isNil(o.UpdateMask) {
    return nil, false
	}
	return o.UpdateMask, true
}

// HasUpdateMask returns a boolean if a field has been set.
func (o *ProductBulkUpdateRequestV2Payload) HasUpdateMask() bool {
	if o != nil && !isNil(o.UpdateMask) {
		return true
	}

	return false
}

// SetUpdateMask gets a reference to the given ProductFieldMask and assigns it to the UpdateMask field.
func (o *ProductBulkUpdateRequestV2Payload) SetUpdateMask(v ProductFieldMask) {
	o.UpdateMask = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ProductBulkUpdateRequestV2Payload) GetAttributes() map[string]ProtobufAny {
	if o == nil || isNil(o.Attributes) {
		var ret map[string]ProtobufAny
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateRequestV2Payload) GetAttributesOk() (*map[string]ProtobufAny, bool) {
	if o == nil || isNil(o.Attributes) {
    return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ProductBulkUpdateRequestV2Payload) HasAttributes() bool {
	if o != nil && !isNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]ProtobufAny and assigns it to the Attributes field.
func (o *ProductBulkUpdateRequestV2Payload) SetAttributes(v map[string]ProtobufAny) {
	o.Attributes = &v
}

func (o ProductBulkUpdateRequestV2Payload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.UpdateMask) {
		toSerialize["updateMask"] = o.UpdateMask
	}
	if !isNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableProductBulkUpdateRequestV2Payload struct {
	value *ProductBulkUpdateRequestV2Payload
	isSet bool
}

func (v NullableProductBulkUpdateRequestV2Payload) Get() *ProductBulkUpdateRequestV2Payload {
	return v.value
}

func (v *NullableProductBulkUpdateRequestV2Payload) Set(val *ProductBulkUpdateRequestV2Payload) {
	v.value = val
	v.isSet = true
}

func (v NullableProductBulkUpdateRequestV2Payload) IsSet() bool {
	return v.isSet
}

func (v *NullableProductBulkUpdateRequestV2Payload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductBulkUpdateRequestV2Payload(val *ProductBulkUpdateRequestV2Payload) *NullableProductBulkUpdateRequestV2Payload {
	return &NullableProductBulkUpdateRequestV2Payload{value: val, isSet: true}
}

func (v NullableProductBulkUpdateRequestV2Payload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductBulkUpdateRequestV2Payload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


