/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the EntitymanagerGetOptionsListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitymanagerGetOptionsListRequest{}

// EntitymanagerGetOptionsListRequest struct for EntitymanagerGetOptionsListRequest
type EntitymanagerGetOptionsListRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	ListCode *string `json:"listCode,omitempty"`
}

// NewEntitymanagerGetOptionsListRequest instantiates a new EntitymanagerGetOptionsListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitymanagerGetOptionsListRequest() *EntitymanagerGetOptionsListRequest {
	this := EntitymanagerGetOptionsListRequest{}
	return &this
}

// NewEntitymanagerGetOptionsListRequestWithDefaults instantiates a new EntitymanagerGetOptionsListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitymanagerGetOptionsListRequestWithDefaults() *EntitymanagerGetOptionsListRequest {
	this := EntitymanagerGetOptionsListRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *EntitymanagerGetOptionsListRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerGetOptionsListRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *EntitymanagerGetOptionsListRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *EntitymanagerGetOptionsListRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetListCode returns the ListCode field value if set, zero value otherwise.
func (o *EntitymanagerGetOptionsListRequest) GetListCode() string {
	if o == nil || IsNil(o.ListCode) {
		var ret string
		return ret
	}
	return *o.ListCode
}

// GetListCodeOk returns a tuple with the ListCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerGetOptionsListRequest) GetListCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ListCode) {
		return nil, false
	}
	return o.ListCode, true
}

// HasListCode returns a boolean if a field has been set.
func (o *EntitymanagerGetOptionsListRequest) HasListCode() bool {
	if o != nil && !IsNil(o.ListCode) {
		return true
	}

	return false
}

// SetListCode gets a reference to the given string and assigns it to the ListCode field.
func (o *EntitymanagerGetOptionsListRequest) SetListCode(v string) {
	o.ListCode = &v
}

func (o EntitymanagerGetOptionsListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitymanagerGetOptionsListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.ListCode) {
		toSerialize["listCode"] = o.ListCode
	}
	return toSerialize, nil
}

type NullableEntitymanagerGetOptionsListRequest struct {
	value *EntitymanagerGetOptionsListRequest
	isSet bool
}

func (v NullableEntitymanagerGetOptionsListRequest) Get() *EntitymanagerGetOptionsListRequest {
	return v.value
}

func (v *NullableEntitymanagerGetOptionsListRequest) Set(val *EntitymanagerGetOptionsListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitymanagerGetOptionsListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitymanagerGetOptionsListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitymanagerGetOptionsListRequest(val *EntitymanagerGetOptionsListRequest) *NullableEntitymanagerGetOptionsListRequest {
	return &NullableEntitymanagerGetOptionsListRequest{value: val, isSet: true}
}

func (v NullableEntitymanagerGetOptionsListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitymanagerGetOptionsListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


