/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the ProductBulkUpdateResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductBulkUpdateResponseV2{}

// ProductBulkUpdateResponseV2 struct for ProductBulkUpdateResponseV2
type ProductBulkUpdateResponseV2 struct {
	ProductResponse []ProductBulkUpdateResponseV2Response `json:"productResponse,omitempty"`
}

// NewProductBulkUpdateResponseV2 instantiates a new ProductBulkUpdateResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductBulkUpdateResponseV2() *ProductBulkUpdateResponseV2 {
	this := ProductBulkUpdateResponseV2{}
	return &this
}

// NewProductBulkUpdateResponseV2WithDefaults instantiates a new ProductBulkUpdateResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductBulkUpdateResponseV2WithDefaults() *ProductBulkUpdateResponseV2 {
	this := ProductBulkUpdateResponseV2{}
	return &this
}

// GetProductResponse returns the ProductResponse field value if set, zero value otherwise.
func (o *ProductBulkUpdateResponseV2) GetProductResponse() []ProductBulkUpdateResponseV2Response {
	if o == nil || IsNil(o.ProductResponse) {
		var ret []ProductBulkUpdateResponseV2Response
		return ret
	}
	return o.ProductResponse
}

// GetProductResponseOk returns a tuple with the ProductResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateResponseV2) GetProductResponseOk() ([]ProductBulkUpdateResponseV2Response, bool) {
	if o == nil || IsNil(o.ProductResponse) {
		return nil, false
	}
	return o.ProductResponse, true
}

// HasProductResponse returns a boolean if a field has been set.
func (o *ProductBulkUpdateResponseV2) HasProductResponse() bool {
	if o != nil && !IsNil(o.ProductResponse) {
		return true
	}

	return false
}

// SetProductResponse gets a reference to the given []ProductBulkUpdateResponseV2Response and assigns it to the ProductResponse field.
func (o *ProductBulkUpdateResponseV2) SetProductResponse(v []ProductBulkUpdateResponseV2Response) {
	o.ProductResponse = v
}

func (o ProductBulkUpdateResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductBulkUpdateResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductResponse) {
		toSerialize["productResponse"] = o.ProductResponse
	}
	return toSerialize, nil
}

type NullableProductBulkUpdateResponseV2 struct {
	value *ProductBulkUpdateResponseV2
	isSet bool
}

func (v NullableProductBulkUpdateResponseV2) Get() *ProductBulkUpdateResponseV2 {
	return v.value
}

func (v *NullableProductBulkUpdateResponseV2) Set(val *ProductBulkUpdateResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableProductBulkUpdateResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableProductBulkUpdateResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductBulkUpdateResponseV2(val *ProductBulkUpdateResponseV2) *NullableProductBulkUpdateResponseV2 {
	return &NullableProductBulkUpdateResponseV2{value: val, isSet: true}
}

func (v NullableProductBulkUpdateResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductBulkUpdateResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


