/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the EntitymanagerListOptionsListsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitymanagerListOptionsListsRequest{}

// EntitymanagerListOptionsListsRequest struct for EntitymanagerListOptionsListsRequest
type EntitymanagerListOptionsListsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
}

// NewEntitymanagerListOptionsListsRequest instantiates a new EntitymanagerListOptionsListsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitymanagerListOptionsListsRequest() *EntitymanagerListOptionsListsRequest {
	this := EntitymanagerListOptionsListsRequest{}
	return &this
}

// NewEntitymanagerListOptionsListsRequestWithDefaults instantiates a new EntitymanagerListOptionsListsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitymanagerListOptionsListsRequestWithDefaults() *EntitymanagerListOptionsListsRequest {
	this := EntitymanagerListOptionsListsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *EntitymanagerListOptionsListsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerListOptionsListsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *EntitymanagerListOptionsListsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *EntitymanagerListOptionsListsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

func (o EntitymanagerListOptionsListsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitymanagerListOptionsListsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	return toSerialize, nil
}

type NullableEntitymanagerListOptionsListsRequest struct {
	value *EntitymanagerListOptionsListsRequest
	isSet bool
}

func (v NullableEntitymanagerListOptionsListsRequest) Get() *EntitymanagerListOptionsListsRequest {
	return v.value
}

func (v *NullableEntitymanagerListOptionsListsRequest) Set(val *EntitymanagerListOptionsListsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitymanagerListOptionsListsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitymanagerListOptionsListsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitymanagerListOptionsListsRequest(val *EntitymanagerListOptionsListsRequest) *NullableEntitymanagerListOptionsListsRequest {
	return &NullableEntitymanagerListOptionsListsRequest{value: val, isSet: true}
}

func (v NullableEntitymanagerListOptionsListsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitymanagerListOptionsListsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


