/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the ProductGetProductByCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductGetProductByCodeResponse{}

// ProductGetProductByCodeResponse struct for ProductGetProductByCodeResponse
type ProductGetProductByCodeResponse struct {
	Product *ProductProductEntity `json:"product,omitempty"`
}

// NewProductGetProductByCodeResponse instantiates a new ProductGetProductByCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductGetProductByCodeResponse() *ProductGetProductByCodeResponse {
	this := ProductGetProductByCodeResponse{}
	return &this
}

// NewProductGetProductByCodeResponseWithDefaults instantiates a new ProductGetProductByCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductGetProductByCodeResponseWithDefaults() *ProductGetProductByCodeResponse {
	this := ProductGetProductByCodeResponse{}
	return &this
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *ProductGetProductByCodeResponse) GetProduct() ProductProductEntity {
	if o == nil || IsNil(o.Product) {
		var ret ProductProductEntity
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductGetProductByCodeResponse) GetProductOk() (*ProductProductEntity, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *ProductGetProductByCodeResponse) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given ProductProductEntity and assigns it to the Product field.
func (o *ProductGetProductByCodeResponse) SetProduct(v ProductProductEntity) {
	o.Product = &v
}

func (o ProductGetProductByCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductGetProductByCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	return toSerialize, nil
}

type NullableProductGetProductByCodeResponse struct {
	value *ProductGetProductByCodeResponse
	isSet bool
}

func (v NullableProductGetProductByCodeResponse) Get() *ProductGetProductByCodeResponse {
	return v.value
}

func (v *NullableProductGetProductByCodeResponse) Set(val *ProductGetProductByCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductGetProductByCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductGetProductByCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductGetProductByCodeResponse(val *ProductGetProductByCodeResponse) *NullableProductGetProductByCodeResponse {
	return &NullableProductGetProductByCodeResponse{value: val, isSet: true}
}

func (v NullableProductGetProductByCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductGetProductByCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


