/*
product/product.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// EntitymanagerGetAttributeOptionsResponseOption struct for EntitymanagerGetAttributeOptionsResponseOption
type EntitymanagerGetAttributeOptionsResponseOption struct {
	ListCode *string `json:"listCode,omitempty"`
	Option *EntitymanagerAttributeOption `json:"option,omitempty"`
}

// NewEntitymanagerGetAttributeOptionsResponseOption instantiates a new EntitymanagerGetAttributeOptionsResponseOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitymanagerGetAttributeOptionsResponseOption() *EntitymanagerGetAttributeOptionsResponseOption {
	this := EntitymanagerGetAttributeOptionsResponseOption{}
	return &this
}

// NewEntitymanagerGetAttributeOptionsResponseOptionWithDefaults instantiates a new EntitymanagerGetAttributeOptionsResponseOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitymanagerGetAttributeOptionsResponseOptionWithDefaults() *EntitymanagerGetAttributeOptionsResponseOption {
	this := EntitymanagerGetAttributeOptionsResponseOption{}
	return &this
}

// GetListCode returns the ListCode field value if set, zero value otherwise.
func (o *EntitymanagerGetAttributeOptionsResponseOption) GetListCode() string {
	if o == nil || isNil(o.ListCode) {
		var ret string
		return ret
	}
	return *o.ListCode
}

// GetListCodeOk returns a tuple with the ListCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerGetAttributeOptionsResponseOption) GetListCodeOk() (*string, bool) {
	if o == nil || isNil(o.ListCode) {
    return nil, false
	}
	return o.ListCode, true
}

// HasListCode returns a boolean if a field has been set.
func (o *EntitymanagerGetAttributeOptionsResponseOption) HasListCode() bool {
	if o != nil && !isNil(o.ListCode) {
		return true
	}

	return false
}

// SetListCode gets a reference to the given string and assigns it to the ListCode field.
func (o *EntitymanagerGetAttributeOptionsResponseOption) SetListCode(v string) {
	o.ListCode = &v
}

// GetOption returns the Option field value if set, zero value otherwise.
func (o *EntitymanagerGetAttributeOptionsResponseOption) GetOption() EntitymanagerAttributeOption {
	if o == nil || isNil(o.Option) {
		var ret EntitymanagerAttributeOption
		return ret
	}
	return *o.Option
}

// GetOptionOk returns a tuple with the Option field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerGetAttributeOptionsResponseOption) GetOptionOk() (*EntitymanagerAttributeOption, bool) {
	if o == nil || isNil(o.Option) {
    return nil, false
	}
	return o.Option, true
}

// HasOption returns a boolean if a field has been set.
func (o *EntitymanagerGetAttributeOptionsResponseOption) HasOption() bool {
	if o != nil && !isNil(o.Option) {
		return true
	}

	return false
}

// SetOption gets a reference to the given EntitymanagerAttributeOption and assigns it to the Option field.
func (o *EntitymanagerGetAttributeOptionsResponseOption) SetOption(v EntitymanagerAttributeOption) {
	o.Option = &v
}

func (o EntitymanagerGetAttributeOptionsResponseOption) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ListCode) {
		toSerialize["listCode"] = o.ListCode
	}
	if !isNil(o.Option) {
		toSerialize["option"] = o.Option
	}
	return json.Marshal(toSerialize)
}

type NullableEntitymanagerGetAttributeOptionsResponseOption struct {
	value *EntitymanagerGetAttributeOptionsResponseOption
	isSet bool
}

func (v NullableEntitymanagerGetAttributeOptionsResponseOption) Get() *EntitymanagerGetAttributeOptionsResponseOption {
	return v.value
}

func (v *NullableEntitymanagerGetAttributeOptionsResponseOption) Set(val *EntitymanagerGetAttributeOptionsResponseOption) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitymanagerGetAttributeOptionsResponseOption) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitymanagerGetAttributeOptionsResponseOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitymanagerGetAttributeOptionsResponseOption(val *EntitymanagerGetAttributeOptionsResponseOption) *NullableEntitymanagerGetAttributeOptionsResponseOption {
	return &NullableEntitymanagerGetAttributeOptionsResponseOption{value: val, isSet: true}
}

func (v NullableEntitymanagerGetAttributeOptionsResponseOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitymanagerGetAttributeOptionsResponseOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


