/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the EntitymanagerListAttributeGroupsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitymanagerListAttributeGroupsRequest{}

// EntitymanagerListAttributeGroupsRequest struct for EntitymanagerListAttributeGroupsRequest
type EntitymanagerListAttributeGroupsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
}

// NewEntitymanagerListAttributeGroupsRequest instantiates a new EntitymanagerListAttributeGroupsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitymanagerListAttributeGroupsRequest() *EntitymanagerListAttributeGroupsRequest {
	this := EntitymanagerListAttributeGroupsRequest{}
	return &this
}

// NewEntitymanagerListAttributeGroupsRequestWithDefaults instantiates a new EntitymanagerListAttributeGroupsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitymanagerListAttributeGroupsRequestWithDefaults() *EntitymanagerListAttributeGroupsRequest {
	this := EntitymanagerListAttributeGroupsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *EntitymanagerListAttributeGroupsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitymanagerListAttributeGroupsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *EntitymanagerListAttributeGroupsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *EntitymanagerListAttributeGroupsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

func (o EntitymanagerListAttributeGroupsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitymanagerListAttributeGroupsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	return toSerialize, nil
}

type NullableEntitymanagerListAttributeGroupsRequest struct {
	value *EntitymanagerListAttributeGroupsRequest
	isSet bool
}

func (v NullableEntitymanagerListAttributeGroupsRequest) Get() *EntitymanagerListAttributeGroupsRequest {
	return v.value
}

func (v *NullableEntitymanagerListAttributeGroupsRequest) Set(val *EntitymanagerListAttributeGroupsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitymanagerListAttributeGroupsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitymanagerListAttributeGroupsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitymanagerListAttributeGroupsRequest(val *EntitymanagerListAttributeGroupsRequest) *NullableEntitymanagerListAttributeGroupsRequest {
	return &NullableEntitymanagerListAttributeGroupsRequest{value: val, isSet: true}
}

func (v NullableEntitymanagerListAttributeGroupsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitymanagerListAttributeGroupsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


