/*
Product Service

API for managing products

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// checks if the ProductLocalizedText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductLocalizedText{}

// ProductLocalizedText struct for ProductLocalizedText
type ProductLocalizedText struct {
	Value *map[string]string `json:"value,omitempty"`
}

// NewProductLocalizedText instantiates a new ProductLocalizedText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductLocalizedText() *ProductLocalizedText {
	this := ProductLocalizedText{}
	return &this
}

// NewProductLocalizedTextWithDefaults instantiates a new ProductLocalizedText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductLocalizedTextWithDefaults() *ProductLocalizedText {
	this := ProductLocalizedText{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ProductLocalizedText) GetValue() map[string]string {
	if o == nil || IsNil(o.Value) {
		var ret map[string]string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductLocalizedText) GetValueOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ProductLocalizedText) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]string and assigns it to the Value field.
func (o *ProductLocalizedText) SetValue(v map[string]string) {
	o.Value = &v
}

func (o ProductLocalizedText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductLocalizedText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableProductLocalizedText struct {
	value *ProductLocalizedText
	isSet bool
}

func (v NullableProductLocalizedText) Get() *ProductLocalizedText {
	return v.value
}

func (v *NullableProductLocalizedText) Set(val *ProductLocalizedText) {
	v.value = val
	v.isSet = true
}

func (v NullableProductLocalizedText) IsSet() bool {
	return v.isSet
}

func (v *NullableProductLocalizedText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductLocalizedText(val *ProductLocalizedText) *NullableProductLocalizedText {
	return &NullableProductLocalizedText{value: val, isSet: true}
}

func (v NullableProductLocalizedText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductLocalizedText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


