/*
product/product.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product

import (
	"encoding/json"
)

// ProductBulkUpdateRequest struct for ProductBulkUpdateRequest
type ProductBulkUpdateRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	ProductIds []string `json:"productIds,omitempty"`
	Payload *BulkUpdateRequestPayload `json:"payload,omitempty"`
}

// NewProductBulkUpdateRequest instantiates a new ProductBulkUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductBulkUpdateRequest() *ProductBulkUpdateRequest {
	this := ProductBulkUpdateRequest{}
	return &this
}

// NewProductBulkUpdateRequestWithDefaults instantiates a new ProductBulkUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductBulkUpdateRequestWithDefaults() *ProductBulkUpdateRequest {
	this := ProductBulkUpdateRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductBulkUpdateRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductBulkUpdateRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductBulkUpdateRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetProductIds returns the ProductIds field value if set, zero value otherwise.
func (o *ProductBulkUpdateRequest) GetProductIds() []string {
	if o == nil || isNil(o.ProductIds) {
		var ret []string
		return ret
	}
	return o.ProductIds
}

// GetProductIdsOk returns a tuple with the ProductIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateRequest) GetProductIdsOk() ([]string, bool) {
	if o == nil || isNil(o.ProductIds) {
    return nil, false
	}
	return o.ProductIds, true
}

// HasProductIds returns a boolean if a field has been set.
func (o *ProductBulkUpdateRequest) HasProductIds() bool {
	if o != nil && !isNil(o.ProductIds) {
		return true
	}

	return false
}

// SetProductIds gets a reference to the given []string and assigns it to the ProductIds field.
func (o *ProductBulkUpdateRequest) SetProductIds(v []string) {
	o.ProductIds = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *ProductBulkUpdateRequest) GetPayload() BulkUpdateRequestPayload {
	if o == nil || isNil(o.Payload) {
		var ret BulkUpdateRequestPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductBulkUpdateRequest) GetPayloadOk() (*BulkUpdateRequestPayload, bool) {
	if o == nil || isNil(o.Payload) {
    return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *ProductBulkUpdateRequest) HasPayload() bool {
	if o != nil && !isNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given BulkUpdateRequestPayload and assigns it to the Payload field.
func (o *ProductBulkUpdateRequest) SetPayload(v BulkUpdateRequestPayload) {
	o.Payload = &v
}

func (o ProductBulkUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.ProductIds) {
		toSerialize["productIds"] = o.ProductIds
	}
	if !isNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return json.Marshal(toSerialize)
}

type NullableProductBulkUpdateRequest struct {
	value *ProductBulkUpdateRequest
	isSet bool
}

func (v NullableProductBulkUpdateRequest) Get() *ProductBulkUpdateRequest {
	return v.value
}

func (v *NullableProductBulkUpdateRequest) Set(val *ProductBulkUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductBulkUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductBulkUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductBulkUpdateRequest(val *ProductBulkUpdateRequest) *NullableProductBulkUpdateRequest {
	return &NullableProductBulkUpdateRequest{value: val, isSet: true}
}

func (v NullableProductBulkUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductBulkUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


